//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package org.esaip.messenger;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.EditText;
import com.googlecode.androidannotations.api.BackgroundExecutor;
import org.esaip.messenger.R.id;
import org.esaip.messenger.R.layout;
import org.esaip.messenger.rest.RestClient_;
import org.esaip.messenger.util.MyPrefs_;

public final class Envoi_
    extends Envoi
{

    private Handler handler_ = new Handler();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.envoi);
    }

    private void init_(Bundle savedInstanceState) {
        sprefs = new MyPrefs_(this);
        myRestClient = new RestClient_();
    }

    private void afterSetContentView_() {
        bEnvoyerMsg = ((Button) findViewById(id.bEnvoyerMsg));
        messagetosend = ((EditText) findViewById(id.messagetosend));
        {
            View view = findViewById(id.bEnvoyerMsg);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        Envoi_.this.send();
                    }

                }
                );
            }
        }
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static Envoi_.IntentBuilder_ intent(Context context) {
        return new Envoi_.IntentBuilder_(context);
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        MenuInflater menuInflater = getMenuInflater();
        menuInflater.inflate(org.esaip.messenger.R.menu.menuconnected, menu);
        return super.onCreateOptionsMenu(menu);
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        boolean handled = super.onOptionsItemSelected(item);
        if (handled) {
            return true;
        }
        int itemId_ = item.getItemId();
        if (itemId_ == id.deco) {
            decoSelected();
            return true;
        }
        return false;
    }

    @Override
    public void updateui() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    Envoi_.super.updateui();
                } catch (RuntimeException e) {
                    Log.e("Envoi_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void sendmessage() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    Envoi_.super.sendmessage();
                } catch (RuntimeException e) {
                    Log.e("Envoi_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, Envoi_.class);
        }

        public Intent get() {
            return intent_;
        }

        public Envoi_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
